//Different manufacturers of cyberware
#define CYBERWARE_DEFAULT "default"
#define CYBERWARE_ATUA "ATUA SYNKINETICS"
#define CYBERWARE_DRAGONFANG "DRAGONFANG CYBER-DESIGN"
#define CYBERWARE_LANCASTER "LANCASTER MECHANICS"
#define CYBERWARE_MIDISED "MIDITEKE-SEDARI TOKOCE"
#define CYBERWARE_CYBERSUN "CYBERSUN BIODYNAMICS"
#define CYBERWARE_RACHNIDGUILD "rachnid guild placeholder"
